# Generated by Django 4.2.4 on 2024-01-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='whatsapp',
        ),
    ]
