# Generated by Django 4.2.4 on 2024-01-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_rename_apellido_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
